[directory]
truncate_to_repo = false
truncation_length = 5
format = " [$path]($style)[$read_only]($read_only_style) "

[character]
success_symbol = "[ ğŸ• â¯](bold green)"
error_symbol = "[ ğŸ• â¯](bold red)"

[dotnet]
symbol = "îœŒ "
format = "with [(dotnet $symbol$tfm )]($style)"

[nodejs]
format = "with [nodejs $symbol$version]($style)"

[git_status]
conflicted = "ğŸ˜µ[$count](orange)"
ahead = "ï…¶$count(orange)"
behind = "ï…µ$count(purple)"
diverged = "ğŸ¤¦(ahead_count|$behind_count)(purple)"
untracked = "[ğŸ†•â€$count](yellow)"
stashed = "ğŸ“¦"
modified = "[~$count](yellow)"
staged = "[âœ”$count](green)"
renamed = "ğŸ‘…[~$count)](yellow)"
deleted = "âŒ[$count](red)"
